<?php

namespace OC\AdminBundle\Repository;

/**
 * AppoinmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppoinmentRepository extends \Doctrine\ORM\EntityRepository
{
}
